export enum USER_ROLES {
  SUPER_ADMIN = 'SUPER_ADMIN',
  POSTER = 'POSTER',
  TASKER = 'TASKER',
  GUEST = 'GUEST',
}

export enum USER_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  RESTRICTED = 'RESTRICTED',
  DELETE = 'DELETE',
}
